# Generated by Django 5.2.8 on 2025-11-12 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tallercostura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('especialidad', models.CharField(max_length=100)),
                ('fecha_contratacion', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('proveedor', models.CharField(max_length=100)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_compra', models.DateField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='app_tallercostura.clase')),
            ],
        ),
    ]
