# Generated by Django 5.2.8 on 2025-11-12 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tallercostura', '0002_profesor_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='clases',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='clase',
            name='alumnos',
            field=models.ManyToManyField(related_name='clases', through='app_tallercostura.Inscripcion', to='app_tallercostura.alumno'),
        ),
        migrations.AddField(
            model_name='clase',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases', to='app_tallercostura.profesor'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='cupo_maximo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clase',
            name='duracion_horas',
            field=models.IntegerField(),
        ),
    ]
